# Generated by Django 5.0.3 on 2024-03-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='new_book',
            name='updated_at',
        ),
    ]
