# Generated by Django 5.0.3 on 2024-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_new_book_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_book',
            name='creared_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='new_book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
