# Generated by Django 5.0.3 on 2024-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_new_book_creared_at_new_book_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_book',
            name='image',
            field=models.ImageField(null=True, upload_to='bookstore/images/'),
        ),
    ]
